=== Zeppier/SAX-dtd-xsd-parser/src/main/resources/securityspace.dtd
<!ELEMENT securityspace (telegram*,server)>
<!ATTLIST securityspace
        xmlns CDATA #REQUIRED>

<!ELEMENT telegram (user,messages)>
<!ATTLIST telegram
  userid CDATA #REQUIRED>

<!ELEMENT user (#PCDATA)>

<!ELEMENT messages (notification*,systemMessage*)>

<!ELEMENT notification (type,time,imageUrl)>

<!ELEMENT type (#PCDATA)>

<!ELEMENT time (#PCDATA)>

<!ELEMENT imageUrl (#PCDATA)>

<!ELEMENT systemMessage (text,time)>

<!ELEMENT text (#PCDATA)>

<!ELEMENT server (RTSP_stream*)>

<!ELEMENT RTSP_stream (link,owner,quality,settings)>
<!ATTLIST RTSP_stream
      userId CDATA #REQUIRED>
<!ELEMENT link (#PCDATA)>

<!ELEMENT owner (#PCDATA)>

<!ELEMENT quality (#PCDATA)>

<!ELEMENT settings (moveDetection,blurDetection)>

<!ELEMENT button (#PCDATA)>

<!ELEMENT command (#PCDATA)>

<!ELEMENT moveDetection (#PCDATA)>

<!ELEMENT blurDetection (#PCDATA)>

=== Zeppier/SAX-dtd-xsd-parser/src/main/resources/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE securityspace SYSTEM "securityspace.dtd">

<securityspace xmlns="securityspace.xsd">
    <telegram userid="1">
        <user>telegramuser1</user>
        <messages>

            <notification>
                <type>Motion detected</type>
                <time>11.09.2020 17:47 EEST</time>
                <imageUrl>https://example.url/image2.jpg</imageUrl>
            </notification>
            <systemMessage>
                <text>Link setted successfuly</text>
                <time>11.09.2020 17:45 EEST</time>
            </systemMessage>
        </messages>
    </telegram>
    <server>
        <RTSP_stream userid="1">
            <notification>
                <type>Image blurred</type>
                <time>11.09.2020 17:48 EEST</time>
                <imageUrl>https://example.url/image1.jpg</imageUrl>
            </notification>
            <link>rtsp://example.com/rtsp1</link>
            <owner>telegramuser1</owner>
            <quality>360p</quality>
            <settings>
                <moveDetection>false</moveDetection>
                <blurDetection>true</blurDetection>
            </settings>
        </RTSP_stream>
        <RTSP_stream userid="1">
            <link>rtsp://example.com/rtsp2</link>
            <owner>telegramuser2</owner>
            <quality>144p</quality>
            <settings>
                <moveDetection>true</moveDetection>
                <blurDetection>true</blurDetection>
            </settings>
        </RTSP_stream>
    </server>
</securityspace>
